# Generated by Django 5.2.12 on 2026-08-22 03:31

import django.db.models.deletion
import utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjallocation', '0010_alter_adjudicatoradjudicatorconflict_unique_together_and_more'),
        ('participants', '0030_adjudicator_registration_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjudicatorRequirementAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjudicator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='participants.adjudicator', verbose_name='adjudicator')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participants.institution', verbose_name='institution')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participants.team', verbose_name='team')),
            ],
            options={
                'verbose_name': 'adjudicator requirement assignment',
                'verbose_name_plural': 'adjudicator requirement assignments',
            },
        ),
        migrations.CreateModel(
            name='AdjudicatorRequirementException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='exceptions granted')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participants.institution', verbose_name='institution')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participants.team', verbose_name='team')),
            ],
            options={
                'verbose_name': 'adjudicator requirement exception',
                'verbose_name_plural': 'adjudicator requirement exceptions',
                'constraints': [utils.models.UniqueConstraint(fields=('institution',), name='adjallo_adjudicatorrequirementexception_institution_uniq'), utils.models.UniqueConstraint(fields=('team',), name='adjallo_adjudicatorrequirementexception_team_uniq')],
            },
        ),
    ]
